# Benediktova et al. 2020 {#benediktovadogfield}

*Magnetic alignment enhances homing efficiency of hunting dogs* [@benediktova2020magnetic]

- 'homing' behaviour has been shown in many animals, and could be driven by multiple cues. Homing behaviour in non-migratory species still needs to be excplored more. 
- Reports of dogs that found their way back even when displaced beyond their usual home range, and without access to familiar visual cues.
- Hunting dogs have been bred by humans to chase game and then return to the start point if not followed by the hunter. These 'hunts' can ve a few hundreds to thousands of meter long. 
- These dogs may find their way back either using their own scent trail - which the authors called 'tracking' or, by actually navigating using the landmarks or information gained during the onward travel, which the authors call 'scouting'

## Methods 
- The hunting dogs were left to innately follow the olfactory tracks of game animals in the wildlife reserve
- Small dogs were used, and so there was no 'physical threat' to wild animals 
- All dogs were tagged with GPS collars, and some of the trials with dogs also had a camera involved. 
- Trials were performed with single dogs, and in areas free of high voltage power lines, roads or buildings and across the day and season (across the year)
- There needs to be some more clarity in terms of when a trial started (see *Comments*)
- Owners hid behind a tree to reduce visual beaconing
- Only excursions >200 metres were considered for this study 
- Authors split all excursions into 10 equal parts, and assigned phases to them based on the average speed of the part.

###  Return strategies
- Dog return strategies could be categorised into two classes
  - tracking: the inbound and outbound trajectory are the same , and the inbound-outbound trajectories were <30 m apart
  - scouting: a new woute was taken, and the inbound-outbound trajectories were >30 m apart

## Results
- in ~59% of all trials, dogs ended up tracking their way back, while in 33% of the trials, dogs ended up scouting their way back, and in 8% of the trials, dogs used a mic of scouting and tracking 
- Scouting dogs showed a higher average speed while returning (because they tended to take shorter routes)
- Trials bbegan and ended with no particular bias in the compass directions, though trials which were in the north-south axis, showed more efficient homing runs
- wind direction and sun location didn't seem to make a difference
- dogs returning with a scouting strategy seemed to begin by first travelling along the north-south axis, irrespective of the actual location of the destination 

## Discussion
- Authors convincingly rule out the possibility of multiple cues begin used(vision, olfaction, celestial cues). Thedogs are too short to see far, and the forest is pretty opaque. Olfactory cues are likely to change a lot, though one can't rule it out completely
- The sun's location/polarised light -- this they haven't been fully able to elimination - but they indicate that there were trials where the sun wa blocked by clouds - which would reduce the strength of polarised light 'map'
- Authors do highlight the fact that path integration is definitely one possible mechanism by which the dogs in this tudy may be finding their way back, but the question of the north-south run still remains - and it may in fact serve as a kind of recalibration run, over which the errors accumulated over path integration can somehow be 'corrected'? 


## Overall thoughts / Comments
- Really smoth introduction - easy to follow 
- It's not entirely clear how the trial exactly proceeded. The dogs were brought to a site, and then left to roam free. 
  - *The handheld GPS device was programmed to indicate when the dog had travelled ≥100 m from the position of the owner. At this moment (designated as ‘excursion start’) the owners stopped walking...*. This is the confusing part, because, what was the owner doing before that? Were the dog and the owner walking together (unleashed dog) on a trail, and then when the dog roamed far away enough, the trial was considered started. But this still elaves some room for error in terms, of wehere the dog left the 'main trail' and where the owner was when the trial started.....confusing 
- In figure 4, bottom plot - authors plot the *log* of the inbound track length against the raw beeline difference. This is a bit misleading perhaps? In general, yes, the log-transform will tend to show lesser variation - but in general, there will always be a linear correlation between te distance the animal travelled and the beeline distance ...especially if there is some kind of navigation in place... - am I being over-cautious here or not - can't make out. 
-  Pretty cool study, this study ads to the general observation of so many magnetically related behaviours (dogs peeing/pooping facing one direction (where did i read this), arctic foxes always facing one stereotyped direction before ponching onto their prey underneath the snow, and cows facing in one direction while grazing)
