# Schuchmann & Siemers 2010, *PLoS One*

\chaptermark{Horseshoe bat source levels in Bulgaria}

*Variability in Echolocation Call Intensity in a Communityof Horseshoe Bats: A Role for Resource Partitioning orCommunication?* [@schuchmannsiemers2010a]

- *notes taken on 2020-07-23,24*

## Introduction

- Authors measure the source levels of a whole community of horseshoe bats near and around the Tabachka field station. They record call levels of 5 species. 
- The CF distributions of the four-five species that geographically overlap in Europe, also overlap spectrally
- *Rhinolophus mehelyi* can tell apart conspecific calls in the midst of other overlapping species (See comments)
- Do some bats (that are calling at higher than allometrically predicted frequencies) evolve towards a 'private frequency' channel?
- Authors look at whether *R. mehelyi* produce louder calls to compensate for decrease in detection distance because they call at a higher call frequency for their given body size ([Comments 2](#com_shuchsiem))

- The questions the authors ask are:
    - Are the call intensitites different across species, and could call intensities play a role in nice differentiation ([Comments 3](#com_shuchsiem)) 
    - Does *R. mehelyi*, the higher-than-allometrically predicted species, call at 'especially high' call intensities? ([Comments 4](#com_shuchsiem)) 
    - How does max. call intensity vary with body size, sex -- and could it be used as an honest signal bats can use to identify conspecifics ([Comments 5](#com_shuchsiem)) 

## Methods

### Study animals 

- *R. mehelyi, euryale, ferrumequinum, hipposideros* caught from the area around the field station, *R. blasii* caught from the Eastern Rhodopes. 
- Bats recorded in a large-ish room (8x4x2.5m) ([Comments 4](#com_shuchsiem)), and can thus be expected to emit louder calls than when in a cluttered environment

### Call intensitites and acoustic analysis

- Done with a B & K mic placed 1m away fromt he bat's head - *this is a pretty neat and direct way to do it because this is a perching bat anyways!!* ... though, the clutter caused by the mic being right in front of the bat ...hmmm...
- There;s a large variation in the frequency resolution across the years. It also is a bit unclear whether the authors used an automatic or manual method -- though my current reading seems to suggest a semi-manual method to estimate the peak frequency of a call 
- To get call intensity, the authors seem to do a lot of call processing.
    - FIR bandpass filter , with a 128 order bandpass filter([Comments 6](#com_shuchsiem))  and then proceeding to take the FFTs within the call....why do this when you can take the waveform value directly??)
- 

## Results

### Overlap of frequency bands 

- species showed overlap in their CF frequencies 
    - *R. mehelyi, euryale, hipposideros*  overlapped, while those of *R. ferrumequinum* and *R. hipposideros* were different 
- Statistically, the three overlapping species differed (but the sample sizes weren't too big either..)

### Call parameters

- No observed correlation between call intensity and call frequency 
- *R. euryale* seemed to call 10-17 dB lower than the other species. 
- Intra-individual variation of 0-334 Hz across species
-  Intra-individual call intensity variation also of between 2.3 to 5.5 dB 

## Discussion 
- authors suggest call intensity can be an informative cue that can be used to assess species identity. They propose that perching bats may be able to reconstruct the position and 'head-aim' of the other bat, and thus assess its source-level. *While it may be informative to tell apart *R. mehelyi*, which calls fainter than others - there may actually be other cues eg. FM sweeps, or even more 'voice' type characteristics embedded in the whole call that could be picked up by bats themselves?)


### Comments {#com_shuchsiem}

- 1. Need to read ref. 24, Schuchmann & Siemers 2010 (Am. Nat.) - a habituation-dishabituation study
- 2. How does the *allometry* matter per se. The only thing that will matter for the detection distance is the source level and the emitted frequency (unclear)
- 3. It seems a bit tenuous, and obvious- but it's also hard to show a connection well?. Yes, low source level bats may only be able to detect insects from nearby, and high SL bats can detect insects from far away -- not sure, but it sounds vague
- 4. I don't necessarily see a reason for it to call at higher source levels than what other species with similar CF do... not sure, why it would call at 'especially high' call intensities. 
- 5. Probably this is the 'big flight room' at Tabachka?
- 6. Vaguely remember how using a very high order filter can mess with the signal structure itself (altering phases etc.). If the signal structure itself is altered so much, then what is the guarantee that the peak eq. source level obtained in this study is valid? If anything at all, the call intensitites reported in this study may actually be at the lower end of what is known because of the heavy filtering that has been done?
- 7. Odd grammar and typos in a bunch of places.

