# Griffin, Donald, 'Listening in the dark', 

\chaptermark{Listening in the dark}

*Listening in the dark* [@griffin1958listening]

- *notes taken on 2020-11-17*

- *'Echolocation is still a topic that resists neat classification into any conventional category of science. It ramifies into widely different scientific disciplines iunclusing ethology, mammalogy, physiology, psychology, acoustics, nd the mathematical theory of signal detectionl. The results of new investigations have reemphasized the necessity of a broad biological perspective for any serious appreciation of echolocation. *

- page 58: about Spallanzi's work *'Yet only a regrettably small propotion of his obserations and conclusions became widely enough known to win any general acceptance among zoologists, and even today much of his work remains unpublished.What is known of it serves amply to confirm the proposition that one can often learn more from a careful study of the thoughts of a master than from years of firsthand research.'*

- 'The apparatus then in use by Pierce was called a sonic detector, and it consisted of a crystal microphone located at the focus of a long parabolic horn, cacuum tube amplifiers to increase the minute electrical votages generated by such a crystal when ssound waves impinge upon it, and circuit ....'

- page 80: 'And finally, just what can bats perceive by echolocation, how close must objects of various sizes be before they can be detected, under what conditions does echolocation perhaps fail to serve bats as well as in our laboratory tests, and how do dozens or hundreds of bats manage to fly in the same part of a cave without interfering with each other's acoustic orientation?'


- page 85: 'Until very recently only one reliable type of microphone has been available which could be calibrated over the frequency range required to study bat sounds, that is....'

- page 166: 'Echolocation cannot be an easy or an automatic process for the bats; it must require attention, skill, and metnal effort, albeit perhaps wholly unconscious effort like that involved in walking through underbrush or riding a bicycle.'
- page 166: 'Evidently when bats are flying through familiar surroundings they rely to an increasing extent on their memory of spatial relations acquired on previous flights through the same space.'

- page 180, chp 7: 'There were a few practical difficulties standing in the way of this objective. Microphone, pre-amplifier, and portable raio could all be operated from dry batteries, and indeed my original apparatus for listening to bat sounds during their pursuit ofinsects was all carried in a single box strapped to my back by means of a rucksack frame. A cathode ray oscillograph was something else again, but a small one could be operated from a storage batter therough a vibrator which acted as a converter of direct to alternating current. '

- page 181, chp 7: 'Finally after several evenings of hectic preparations and gradual elimination of operating difficulties, I was ready with the microphone and parabolic horn now mounted on a bracket not unlike a tommy gun, the trigger bying a swirch for remote control of the motion picture camera which was to photograph the oscillograph screen.'

- page 201, Chp 7: 'This presented certain difficulties, for people are prone to wonder when a man walks about wearing ear phones connected to a box with dials, and carries in his hand a parabolic horn. Various explanations were suggested quite audibly, but the onlookers seldom noticed the bats though we were pointing the horn toward them at every opportunity. When one youth suggested to his companions that we might be listening to the bats he was derided and drowned out with knowing statements about radio receivers and cosmic rays. '

- page 367, Chp 14: 'To be sure, background noises at ultrasonic frequencies are nto of nearly so great marnitude as sounds of lower frequencies resultring from natural causes such as rustling of begetation by the wind, insect sounds, or the noise produced by running water. But other bats must be a major source of possible interference, and it is only natural to wonder why the many bats whichfly in a single cave do not "jam" each other since each one is busy filling the air with its won pulses.'

- page 386 Chp 15: 'A little of the naturalis'ts viewpoint is required to comprehend more fully the significance and the boundless variety of precisely adapted functional microcosms among which we live. But it is even more obvious in this period of scientific history that we can no longer expect to understand nature by merely describing and cataloging her variety. We now have tools at our disposal which can help us to deeper and more satisfying insights. It is in this context that I hope the phenomena of echolcoation will be contemplated, so that they may serve to exemplify the potential role of an analytical approach to natural history.'

## Chapter 1: The nature of bats

* There is a diurnally active microchiropteran - *Lavia frons*
* Griffin also gives tips for houseowenrs who'd like to get rid of bats in their house - close up the cracks over the winter or when the bats are not roosting. 

## Chapter 3 : The Acoustic Orientation of Bats

* Hahn, an American scientist, had shown the ears of a bat are important for its orientation. He was the first to use the wire-mesh protocol to assess how well bats avoid obstacles.

* So interesting to see that there was a 'rediscovery' of many sorts. Galambos and Griffin also put open/closed tubes onto bat ears o see if that made any difference. 

* Sven Dijkgraf began studies on bats and notice dthe *Ticklaut* - in German occupied Netherlands.

## Chapter 4: The Voices of Bats

* Griffin used cathode ray oscillographs to figure out the call durations of bats. 

* To study the directionality of bat calls - Griffin had to make a bat fly past a camera taking photos, and placed  2 mics at 90 degrees separation! Wow -- and look at me with the *Ushichka* dataset and >10 mics everywhere!!!

## Chapter 5: The hearing of bats

* Mentions issues with figuring outt he behavioural hearing thresholds w animals - esp at freqs where they are not v sensitive - as there may be tonal impurities as certain frequencies are played back at v high thresholds


### Chapter 6: Successs and Failure of Bats' Acoustic Orientation 

* Moehres and Oettingen-Spielberg performed experiments w bats kept over long periods of time, and foudn bats were bery faithful to their own memory. Bats were in fact reluctant to fly into a part of the room where a partition had been removed!  (Möhres, F. P., & Oettingen-Spielberg, T. (1949). Versuche über die Nahorientierung und das Heimfindevermögen der Fledermäuse. Verhandlungen der deutschen Zoologen in Mainz, 248-252.)

* Griffin also describes experiments where he trained an *E. fuscus* to capture prey from the same part of a flight room over a long period, and then put obstacles while the bat was feeding. The bat seemed to constantly crash into the new obstacles - even though it was emitting calls all the time!


### Chapter 7: The pursuit of insect prey

* Spallanzi already did experiments back in teh 1800's where he found agroup of bats - blinded some and left the others as they were. He then compared their stomach contents after capturing them in the morning -and saw the blinded bats had the same number of insects as the ones with intact eyes

* Intersting how Griffin mentions studies where bats were *shot* and their stomach contents examined - it seemed like this kind of approach was fairly common and not so negatively seen as today. 

* Bats seemed to accumulate about 1.3 grams/hour of insects while foraging - data from observational studies looking at stomach contents over the time period from roost emergence

* Exciting descriptions of how the study of echolocation research actually did move from *laboratory* to *field* -- exactly what the whole Ushichka dataset tries to achieve for group echolocation.

* Crazy to think of the kind of basic technology that Griffin had to use to reveal all the things he did! There were *separate* instruments called 'sound spectrographs' which would actually produce spectrograms -- and he writes about how this helped him a lot in studies looking at natural echolocation during insect capture.

* pg 193, 'Experiments with false echoes ' - Griffin writes about his first attempts to create what was later named 'phantom echoes' by Moll?

### Chapter 14: The acuity of echolocation 

* in the section 'The discrimination of echoes from interfering noise': 


