# Moehres & Oettingen-Spielberg 1949, *Verhandlungen der deutschen Zoologen in Mainz*

\chaptermark{Short-range orientation and homing in bats}

*Versuche ueber die Nahorientierung und das Heimfindevermoegen der Fledermauese* [@mohres1949versuche]

- *notes taken on 2020-11-23* (first attempt at reading and making notes for a German paper)

* authors start by stating that many long-distance orientation behaviours are often driven by unknown senses. Studying short range orientation could provide support. 

- Experiments done on *Rhinolophus ferrumequinum* and *Myotis myotis*.

- Many short and long-range orientation bheaviours are driven by the same sensory systems - even though they may predominate differently in each behavioural context. 

- Authors exploit the fact that bats get used to roosting in spot - which can be a cage. They can be made to fly out of the cage by letting out an insect, and then their flight trajectories can be studied over time. 


- The authors make a valid point that closed spaces like flight rooms are indeed very similar to bats' natural environments, as caves are essentially closed spaces. 

## Experiments 

- Authors released bats from a cage to capture insects. They turned the cage door 90degrees to another side while the bat was capturing the insect and observed what the bat actualy did. They found that most of the time the bats constantly attempted to enter the 'wrong' side of the cage - even though they could detect the fact that the current cage surface did not have an opening. 

- Moving and turning the whole cage in the flight room never affected the return flights, as long as the door direction was kept the same

- The authors also began dismantling the cage gradually until there nothing of it anymore. Even then, the bats constantly seemed to return to an imaginary cage and even try to 'hang' from an imaginary ceiling of the cage. 

- Authors also noticed that bats seemed to constantly search for insects in the 'usually' kept places first - and then only look elsewhere. 

- Authors also had a section of the room that was initially inaccessible, and then made accessible. The bats did not fly easily into the part of the room that was later made accessible. Bats always in flew in gradually increasing inward flights, while always returning to their familiar volume. 

## Conclusions
- Authors suggest that bats may use echolocation to first form their impressions of the volume they are flying in. 
- They state it's not possible to directly infer how bats can orient so well in space. 
- They also discuss the possibility of bats reducing/reducing their dependence of echolocation as they gain familiarity with a space they are flying in. 



## Comments 
* Intersting that in this 'report' they talk about how they have just obtained funding from the 'Notgemeinschaft der Deutschen Wissenschaft' and, that they will publish the discussed results in detail in the 'Zeitschrift fuer vergleichende Physiologie' (Now Journal of Comparitive Physiology)



